name: pm4py-gui
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pm4py==2.7.8
      - pandas==2.2.2
      - pyarrow==16.1.0
      - PyQt6==6.7.0
      - pyqtgraph==0.13.7
